name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.8"
      - name: Install poetry
        run: |
          python -m pip install poetry
      - name: Install dependencies
        run: |
          poetry install --no-root
      - name: Init MkDocs
        run: python .mkdocs/scripts/prepare_docs.py
      - name: Build MkDocs
        run: mkdocs build --verbose --clean
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
